### ISSUE TITLE
Publish to JetBrains Marketplace

### ISSUE THREAD

**Issue by AnErrupTion** [FalsePattern/ZigBrains#1]
Hello!

First of all: **thank you** for making this plugin! I actually wanted to make one using LSP4IntellIJ, however I had a few issues, and I noticed your PR on that project. That's when I checked your profile and found this plugin! :)

I'm using it with CLion and it's working great, however, I have a favor to ask: could you please publish this to the JetBrains Marketplace? This way, everyone could download it and it could become the ZLS plugin for IntellIJ-based IDEs!

**Comment by FalsePattern** [comment]
Submitted. Let's hope they don't reject it because of the name.
![image](https://github.com/FalsePattern/ZigBrains/assets/30945458/8e6185fa-a445-4de8-b362-a186598fc1ce)

**Comment by FalsePattern** [comment]
The 0.4.0 github release has been updated with the signed jar and the certificate sent to the marketplace.

**Comment by FalsePattern** [comment]
![IMG_20230811_005058.jpg](https://github.com/FalsePattern/ZigBrains/assets/30945458/c12001e8-3701-4725-9fc2-4b3088338875)

0.4.0 was rejected, lsp4intellij needs to be cleaned up

There were some deprecations and api internalizations in idea since lsp4intellij's original target release (2021.x)

0.5.0 still inherits the internal API usage problems, but i'll try cleaning them up and get 0.5.1 onto the marketplace.

They didn't complain about the project name though, so that's nice.

**Comment by FalsePattern** [comment]
https://plugins.jetbrains.com/plugin/22456-zigbrains

**Comment by AnErrupTion** [comment]
@FalsePattern It seems like I can't install it on CLion because it's "incompatible", but I can install the zip file manually just fine. Is this intended?

**Comment by FalsePattern** [comment]
0.5.1 got unverified because it had a bug, 0.5.2 is still pending verification.
See #2
